server:
  port: 3002
  mode: "debug" # or "release"

database:
  driver: "postgres" # or "mysql"
  dsn: "host=localhost user=sg_admin password=sg_pass_123 dbname=suangongshi port=5432 sslmode=disable TimeZone=Asia/Shanghai"

auth:
  jwt_secret: "your-secret-key" # 用于工人登录态
  token_expire: 72 # Token 有效期(小时)

wechat:
  app_id: "your_appid"
  app_secret: "your_secret"
# oss:
#   endpoint: "oss-cn-hangzhou.aliyuncs.com"
#   bucket_name: "work-proof-photos" # 存储工友打卡照片的桶